# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  datasource:
    url: jdbc:mysql://bh8962.banahosting.com:3306/thfktngb_KillaLibros?useSSL=false&serverTimezone=UTC
    username: thfktngb_lauAdmin
    password: REL131208659297
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect